# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/singer-python"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/tap-git"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/tap-github"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/tap-gitlab"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/tap-jira"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/tap-postgres"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "lib/target-postgres"
    schedule:
      interval: "daily"
