version: '3.8'

x-airflow-common:
  &airflow-common
  environment:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"

networks:
  airflow:

services:
  airflow:
    image: epappas/airflow:latest
    container_name: airflow
    build:
      context: .
      dockerfile: Dockerfile
    <<: *airflow-common
