FROM apache/airflow:2.0.1-python3.7

# ARG PYTHON_BASE_IMAGE="python:3.7-slim-buster"
# ARG PYTHON_MAJOR_MINOR_VERSION=3.7
# ARG AIRFLOW_INSTALLATION_METHOD="apache-airflow"
# ARG AIRFLOW_VERSION="2.0.1"
# ARG AIRFLOW_INSTALL_VERSION="==2.0.1"
# ARG AIRFLOW_CONSTRAINTS_REFERENCE="constraints-2-0"
# ARG ADDITIONAL_AIRFLOW_EXTRAS="jdbc"
# ARG ADDITIONAL_PYTHON_DEPS="pandas"
# ARG ADDITIONAL_DEV_APT_DEPS="gcc g++"
# ARG ADDITIONAL_RUNTIME_APT_DEPS="default-jre-headless"



# ADD requirements.txt /opt/airflow/requirements.txt

# # RUN pip install -U --upgrade --upgrade-strategy eager -r requirements.txt
# # RUN pip install -U -r requirements.txt
# RUN pip install --no-cache-dir --user -r requirements.txt
